#!/bin/sh
# Render a systemd-networkd .network file from an IPv4 pref and apply.
# Usage: networkd-apply-ipv4.sh <iface> <pref-file>
#
# Pref keys (same as eth0-ipv4 / wlan0-ipv4):
#   mode=dhcp|static
#   address=  prefix=  gateway=  dns=
#
# Product contract (dart-hal D11): L3 is systemd-networkd only.
# DNS is systemd-resolved (networkd → resolved → /etc/resolv.conf stub).
# No alternate DHCP clients, raw addressing, or hand-written resolv.conf.
#
# Dual default routes: lower metric wins. Prefer Wi‑Fi (wlan0=100) over
# eth0 (2000) so camera LAN on eth does not steal Internet traffic.
# Wi‑Fi-like metrics (<1000) also set Domains=~. so resolved prefers wlan DNS.
#
# KEEP IN LOCKSTEP with Dart NetworkdIpv4Apply.renderNetworkFile —
# contract tests: packages/cyber_hal/test/networkd_ipv4_apply_test.dart
# (RouteMetric, Domains=~., [DHCPv4] UseDNS, static [Route] Metric).
set -eu

IFACE="${1:-}"
PREF="${2:-}"

log() {
	echo "networkd-apply-ipv4: $*" >&2
}

# systemd-networkd RouteMetric / [Route] Metric — lower = preferred default.
route_metric_for() {
	case "$1" in
	wlan0) echo 100 ;;
	eth0) echo 2000 ;;
	*) echo 500 ;;
	esac
}

if [ -z "$IFACE" ] || [ -z "$PREF" ]; then
	echo "usage: networkd-apply-ipv4.sh <iface> <pref-file>" >&2
	exit 2
fi

case "$IFACE" in
lo|usb0)
	log "refusing $IFACE"
	exit 1
	;;
esac

if ! command -v networkctl >/dev/null 2>&1; then
	log "FATAL: networkctl missing (systemd-networkd required, D11)"
	log "enable BR2_PACKAGE_SYSTEMD_NETWORKD and rebuild:"
	log "  bash scripts/br-make-packages.sh systemd systemd"
	log "  make build-rootfs && make upgrade"
	exit 1
fi

mode=dhcp
address=
prefix=24
gateway=
dns=
if [ -f "$PREF" ]; then
	# shellcheck disable=SC2162
	while IFS='=' read key val; do
		key="$(echo "$key" | tr -d '[:space:]')"
		val="$(echo "$val" | tr -d '\r')"
		case "$key" in
		mode) mode="$(echo "$val" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')" ;;
		address) address="$(echo "$val" | tr -d '[:space:]')" ;;
		prefix) prefix="$(echo "$val" | tr -d '[:space:]')" ;;
		gateway) gateway="$(echo "$val" | tr -d '[:space:]')" ;;
		dns) dns="$(echo "$val" | tr -d '[:space:]')" ;;
		esac
	done <"$PREF"
fi

METRIC="$(route_metric_for "$IFACE")"
# Prefer this link's DNS for unqualified lookups when metric is "wifi-like"
# (see NetworkdIpv4Apply.dnsDefaultRoutePreferred).
DNS_DEFAULT_ROUTE=0
if [ "$METRIC" -lt 1000 ] 2>/dev/null; then
	DNS_DEFAULT_ROUTE=1
fi
OUT="/etc/systemd/network/50-hmi-${IFACE}.network"
mkdir -p /etc/systemd/network

{
	echo "# Generated by networkd-apply-ipv4.sh — do not edit by hand"
	echo "# RouteMetric=${METRIC} (wlan0 preferred over eth0 when both have defaults)"
	echo "[Match]"
	echo "Name=${IFACE}"
	echo
	echo "[Network]"
	case "$mode" in
	static)
		if [ -z "$address" ]; then
			log "static mode missing address"
			exit 1
		fi
		echo "DHCP=no"
		echo "Address=${address}/${prefix:-24}"
		if [ -n "$dns" ]; then
			echo "DNS=${dns}"
		fi
		if [ "$DNS_DEFAULT_ROUTE" -eq 1 ]; then
			echo "Domains=~."
		fi
		if [ -n "$gateway" ]; then
			echo
			echo "[Route]"
			echo "Gateway=${gateway}"
			echo "Metric=${METRIC}"
		fi
		;;
	*)
		echo "DHCP=yes"
		# Prefer IPv4 for the appliance Demo / camera LAN.
		echo "IPv6AcceptRA=no"
		if [ "$DNS_DEFAULT_ROUTE" -eq 1 ]; then
			echo "Domains=~."
		fi
		echo
		echo "[DHCPv4]"
		echo "UseDNS=yes"
		echo "RouteMetric=${METRIC}"
		;;
	esac
} >"$OUT"

log "wrote $OUT ($mode, RouteMetric=${METRIC})"
systemctl start systemd-networkd.service 2>/dev/null || true
systemctl start systemd-resolved.service 2>/dev/null || true
networkctl reload 2>/dev/null || true
# Bring iface under networkd management and apply.
networkctl up "$IFACE" 2>/dev/null || true
networkctl reconfigure "$IFACE" 2>/dev/null || true
case "$mode" in
static)
	;;
*)
	# Force new lease after SSID/BSS change (stale DNS otherwise).
	networkctl renew "$IFACE" 2>/dev/null || true
	;;
esac

# DHCP can complete after reconfigure returns; wait for IPv4 on the iface.
case "$mode" in
static)
	;;
*)
	i=0
	while [ "$i" -lt 40 ]; do
		if networkctl status "$IFACE" 2>/dev/null | grep -q 'Address:.*DHCP4'; then
			break
		fi
		if ip -4 -o addr show dev "$IFACE" 2>/dev/null | grep -q ' inet '; then
			break
		fi
		i=$((i + 1))
		sleep 0.25
	done
	if ! ip -4 -o addr show dev "$IFACE" 2>/dev/null | grep -q ' inet '; then
		log "WARN: no IPv4 yet on $IFACE after DHCP request (carrier/lease pending)"
	fi
	;;
esac
log "ok ($mode on $IFACE)"
