#!/bin/sh
# Render /etc/mediamtx/mediamtx.yaml for IPC PR0/PR1 fan-out.
# Path layout matches lws-ui MediaMtxConfigRenderer, with product deltas:
# - No writeQueueSize:32 (Linux readers drop frames; use MediaMTX default 512).
# - sourceOnDemand: no — mediamtx is already started/stopped by the App when
#   the camera is reachable; eager pull avoids first-viewer connect latency.
# - rtspTransport: udp — short direct eth0 link (same as lws-ui).
# Usage: render-mediamtx-config.sh [camera_ip]
# camera_ip: argv, else CAMERA_IP env, else product.ini camera_ip, else 192.168.1.100
set -eu

OUT="${MEDIAMTX_CONFIG:-/etc/mediamtx/mediamtx.yaml}"
PRODUCT_INI="${PRODUCT_INI:-/var/lib/hal/product.ini}"
DEFAULT_IP="192.168.1.100"

resolve_camera_ip() {
	if [ -n "${1:-}" ]; then
		echo "$1"
		return
	fi
	if [ -n "${CAMERA_IP:-}" ]; then
		echo "$CAMERA_IP"
		return
	fi
	if [ -f "$PRODUCT_INI" ]; then
		val="$(grep -E '^[[:space:]]*camera_ip[[:space:]]*=' "$PRODUCT_INI" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '[:space:]\r')"
		if [ -n "$val" ]; then
			echo "$val"
			return
		fi
	fi
	echo "$DEFAULT_IP"
}

CAMERA_IP="$(resolve_camera_ip "${1:-}")"
mkdir -p "$(dirname "$OUT")"

umask 022
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cat >"$TMP" <<EOF
# Generated by render-mediamtx-config.sh — do not edit by hand
# camera_ip=$CAMERA_IP
logLevel: info
logDestinations: [stdout]
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no

paths:
  camera/pr0:
    source: rtsp://$CAMERA_IP/PR0
    rtspTransport: udp
    sourceOnDemand: no
  camera/pr1:
    source: rtsp://$CAMERA_IP/PR1
    rtspTransport: udp
    sourceOnDemand: no
EOF

# Avoid rewriting an identical file — MediaMTX watches the path and reloads
# (dropping live RTSP sessions) on any mtime change.
if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then
	echo "render-mediamtx-config: unchanged $OUT camera_ip=$CAMERA_IP" >&2
	exit 0
fi

cat "$TMP" >"$OUT"
echo "render-mediamtx-config: wrote $OUT camera_ip=$CAMERA_IP" >&2
