#!/bin/sh
# Start USB MTP gadget (FunctionFS + umtprd) exposing /userdata/storage.
# Requires: libcomposite/configfs, FunctionFS, /usr/bin/umtprd (make build-umtprd).
set -eu

. /usr/libexec/board/paths.sh 2>/dev/null || true

STORAGE="${USB_MTP_STORAGE:-/userdata/storage}"
PIDFILE="${RUN_USB_MTP_PID:-/run/usb-mtp.pid}"
CONF="${ETC_HMI:-/etc/hmi}/mtp/umtprd.conf"
UMTPRD_BIN="${UMTPRD_BIN:-/usr/bin/umtprd}"
GADGET_ROOT="${USB_MTP_GADGET_ROOT:-/sys/kernel/config/usb_gadget/lws-mtp}"
FFS_MOUNT="${USB_MTP_FFS_MOUNT:-/dev/ffs-mtp}"
RUN_FLAG="${RUN_USB_MTP_ACTIVE:-/run/usb-mtp.active}"
LOG="${USB_MTP_LOG:-/var/log/usb-mtp.log}"

log() {
	echo "usb-mtp-start: $*"
}

die() {
	echo "usb-mtp-start: $*" >&2
	exit 1
}

mtp_udc_bound() {
	local bound
	[ -d "$GADGET_ROOT" ] || return 1
	bound="$(tr -d ' \n' <"$GADGET_ROOT/UDC" 2>/dev/null || true)"
	[ -n "$bound" ]
}

mtp_running_ok() {
	local old
	[ -f "$PIDFILE" ] || return 1
	old="$(cat "$PIDFILE" 2>/dev/null || true)"
	[ -n "$old" ] && kill -0 "$old" 2>/dev/null || return 1
	mtp_udc_bound || return 1
	[ -e "$FFS_MOUNT/ep1" ] || return 1
	return 0
}

# Tear down competing g_ether only — avoid soft_connect when nothing is bound
# (host→mtp apply storms were disconnecting a live MTP gadget).
release_g_ether() {
	if systemctl is-active --quiet ssh-debug-usb.service 2>/dev/null ||
		[ -d /sys/module/g_ether ] || [ -d /sys/class/net/usb0 ]; then
		systemctl stop ssh-debug-usb.service 2>/dev/null || true
		if [ -x /usr/libexec/usb/usb-plug-ssh-stop.sh ]; then
			/usr/libexec/usb/usb-plug-ssh-stop.sh >/dev/null 2>&1 || true
		fi
		sleep 0.2
	fi
}

udc_name() {
	local d
	for d in /sys/class/udc/*; do
		[ -e "$d" ] || continue
		basename "$d"
		return 0
	done
	return 1
}

wait_udc() {
	local i=0
	while [ "$i" -lt 40 ]; do
		udc_name >/dev/null 2>&1 && return 0
		sleep 0.1
		i=$((i + 1))
	done
	return 1
}

write_conf() {
	local serial
	serial="$(/usr/libexec/board/read-device-serial.sh 2>/dev/null || echo 0001)"
	mkdir -p "$(dirname "$CONF")"
	cat >"$CONF" <<EOF
# Generated by usb-mtp-start.sh — do not edit by hand while MTP is active.
loop_on_disconnect 1
storage "$STORAGE" "LWS Storage" "rw"
manufacturer "Innohi"
product "LWS Storage"
serial "$serial"
firmware_version "1.0"
mtp_extensions "microsoft.com: 1.0; android.com: 1.0;"
interface "MTP"
usb_vendor_id 0x2207
usb_product_id 0x0011
usb_class 0x6
usb_subclass 0x1
usb_protocol 0x1
usb_dev_version 0x3008
usb_functionfs_mode 0x1
usb_dev_path "$FFS_MOUNT/ep0"
usb_epin_path "$FFS_MOUNT/ep1"
usb_epout_path "$FFS_MOUNT/ep2"
usb_epint_path "$FFS_MOUNT/ep3"
usb_max_packet_size 0x200
EOF
}

teardown_gadget() {
	if [ -d "$GADGET_ROOT" ]; then
		echo "" >"$GADGET_ROOT/UDC" 2>/dev/null || true
		rm -f "$GADGET_ROOT/configs/c.1/ffs.mtp" 2>/dev/null || true
		rmdir "$GADGET_ROOT/functions/ffs.mtp" 2>/dev/null || true
		rmdir "$GADGET_ROOT/configs/c.1/strings/0x409" 2>/dev/null || true
		rmdir "$GADGET_ROOT/configs/c.1" 2>/dev/null || true
		rmdir "$GADGET_ROOT/strings/0x409" 2>/dev/null || true
		rmdir "$GADGET_ROOT" 2>/dev/null || true
	fi
	if grep -q " ${FFS_MOUNT} " /proc/mounts 2>/dev/null; then
		umount "$FFS_MOUNT" 2>/dev/null || true
	fi
}

setup_gadget() {
	local udc
	wait_udc || die "no UDC under /sys/class/udc (otg still host?)"
	udc="$(udc_name)" || die "no UDC under /sys/class/udc"
	modprobe libcomposite 2>/dev/null || true
	modprobe usb_f_fs 2>/dev/null || true
	modprobe functionfs 2>/dev/null || true

	if [ ! -d /sys/kernel/config/usb_gadget ]; then
		mount -t configfs none /sys/kernel/config 2>/dev/null || true
	fi
	[ -d /sys/kernel/config/usb_gadget ] || die "configfs usb_gadget missing"

	teardown_gadget

	mkdir -p "$GADGET_ROOT"
	cd "$GADGET_ROOT"
	mkdir -p configs/c.1/strings/0x409
	mkdir -p functions/ffs.mtp
	mkdir -p strings/0x409

	# Match umtprd.conf VID/PID (Rockchip vendor + MTP product).
	echo 0x2207 >idVendor
	echo 0x0011 >idProduct
	echo 0x0100 >bcdDevice
	echo 0x0200 >bcdUSB

	serial="$(/usr/libexec/board/read-device-serial.sh 2>/dev/null || echo 0001)"
	echo "$serial" >strings/0x409/serialnumber
	echo "Innohi" >strings/0x409/manufacturer
	echo "LWS Storage" >strings/0x409/product

	echo "Conf 1" >configs/c.1/strings/0x409/configuration
	echo 120 >configs/c.1/MaxPower
	ln -s functions/ffs.mtp configs/c.1/

	mkdir -p "$FFS_MOUNT"
	mount -t functionfs mtp "$FFS_MOUNT"
	log "FunctionFS mounted at $FFS_MOUNT (udc=$udc)"
}

wait_umtprd_ready() {
	local pid="$1" i=0
	# umtprd must write FunctionFS descriptors (ep1 appears) before UDC bind.
	while [ "$i" -lt 50 ]; do
		if ! kill -0 "$pid" 2>/dev/null; then
			echo "usb-mtp-start: umtprd exited early; last log:" >&2
			tail -20 "$LOG" 2>/dev/null >&2 || true
			return 1
		fi
		if [ -e "$FFS_MOUNT/ep1" ]; then
			return 0
		fi
		sleep 0.1
		i=$((i + 1))
	done
	echo "usb-mtp-start: timeout waiting for FunctionFS endpoints" >&2
	tail -20 "$LOG" 2>/dev/null >&2 || true
	return 1
}

bind_udc() {
	local udc
	udc="$(udc_name)" || die "no UDC to bind"
	if ! echo "$udc" >"$GADGET_ROOT/UDC"; then
		die "failed to bind UDC=$udc (busy or FunctionFS not ready?)"
	fi
	log "bound UDC=$udc"
}

mkdir -p "$STORAGE"
[ -x "$UMTPRD_BIN" ] || die "MTP responder missing ($UMTPRD_BIN); run: make build-umtprd"

# Healthy instance: keep it (udev apply storms must not soft-disconnect + no-op).
if mtp_running_ok; then
	log "already running pid=$(cat "$PIDFILE") udc=$(tr -d ' \n' <"$GADGET_ROOT/UDC")"
	exit 0
fi

# Stale pid / unbound UDC → full restart.
if [ -f "$PIDFILE" ]; then
	old="$(cat "$PIDFILE" 2>/dev/null || true)"
	if [ -n "$old" ] && kill -0 "$old" 2>/dev/null; then
		log "restarting stale MTP (pid=$old, UDC not bound)"
		if [ -x /usr/libexec/usb/usb-mtp-stop.sh ]; then
			/usr/libexec/usb/usb-mtp-stop.sh >/dev/null 2>&1 || true
		fi
	else
		rm -f "$PIDFILE"
	fi
fi

release_g_ether
write_conf
setup_gadget

: >"$LOG"
"$UMTPRD_BIN" -conf "$CONF" >>"$LOG" 2>&1 &
echo $! >"$PIDFILE"
if ! wait_umtprd_ready "$(cat "$PIDFILE")"; then
	kill "$(cat "$PIDFILE")" 2>/dev/null || true
	rm -f "$PIDFILE"
	teardown_gadget
	die "umtprd failed to become ready"
fi
touch "$RUN_FLAG"
bind_udc
log "umtprd pid=$(cat "$PIDFILE") storage=$STORAGE conf=$CONF"
