#!/bin/sh
# Apply /var/lib/hal/input.conf → udev LIBINPUT_IGNORE_DEVICE + Weston refresh.
set -eu

. /usr/libexec/board/paths.sh 2>/dev/null || true
PREF_DIR="${VAR_HAL:-/var/lib/hal}"
INPUT_CONF="$PREF_DIR/input.conf"
UDEV_RULES=/etc/udev/rules.d/99-lws-physical-input.rules
WESTON_CFG=/usr/libexec/display/weston-hmi-config.sh
RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/0}"
WESTON_INI="$RUNTIME_DIR/weston.ini"

log() {
	echo "apply-physical-input-policy: $*" >&2
}

input_enabled() {
	key="$1"
	default="${2:-1}"
	if [ ! -f "$INPUT_CONF" ]; then
		printf '%s\n' "$default"
		return 0
	fi
	raw="$(grep -E "^${key}=" "$INPUT_CONF" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '[:space:]')"
	case "$raw" in
	0 | false | FALSE | no | NO | off | OFF) printf '0\n' ;;
	1 | true | TRUE | yes | YES | on | ON) printf '1\n' ;;
	'') printf '%s\n' "$default" ;;
	*) printf '%s\n' "$default" ;;
	esac
}

write_udev_rules() {
	kb="$1"
	mouse="$2"
	if [ "$kb" -eq 1 ] && [ "$mouse" -eq 1 ]; then
		rm -f "$UDEV_RULES"
		log "both enabled — removed $UDEV_RULES"
		return 0
	fi
	mkdir -p "$(dirname "$UDEV_RULES")"
	{
		echo '# Generated by apply-physical-input-policy.sh — do not edit.'
		if [ "$mouse" -eq 0 ]; then
			echo 'SUBSYSTEM=="input", ENV{ID_INPUT_MOUSE}=="1", ENV{LIBINPUT_IGNORE_DEVICE}="1"'
		fi
		if [ "$kb" -eq 0 ]; then
			echo 'SUBSYSTEM=="input", ENV{ID_INPUT_KEYBOARD}=="1", ENV{LIBINPUT_IGNORE_DEVICE}="1", NAME!="gpio-keys", NAME!="adc-keys", NAME!="rk817 pwrkey", NAME!="rk809 pwrkey", NAME!="bt-powerkey", NAME!="pwrkey", NAME!="power-key"'
		fi
	} >"$UDEV_RULES"
	log "wrote $UDEV_RULES (keyboard=$kb mouse=$mouse)"
}

reload_udev() {
	if ! command -v udevadm >/dev/null 2>&1; then
		return 0
	fi
	udevadm control --reload-rules 2>/dev/null || true
	udevadm trigger -s input 2>/dev/null || udevadm trigger 2>/dev/null || true
}

refresh_weston_ini() {
	if [ "${INPUT_UDEV_ONLY:-0}" = "1" ]; then
		return 1
	fi
	if [ ! -x /usr/bin/weston ] || [ ! -f "$WESTON_CFG" ]; then
		return 0
	fi
	transform=rotate-270
	if [ -f "$WESTON_INI" ]; then
		t="$(grep -E '^transform=' "$WESTON_INI" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '[:space:]')"
		if [ -n "$t" ]; then
			transform="$t"
		fi
	fi
	export MOUSE_CONF="${PREF_DIR}/mouse.conf"
	BOARD_ID=""
	if [ -f "${RUN_HMI:-/run/hmi}/oem.env" ]; then
		# shellcheck disable=SC1090
		. "${RUN_HMI:-/run/hmi}/oem.env" 2>/dev/null || true
		BOARD_ID="${BOARD_ID:-}"
	fi
	export BOARD_ID
	# shellcheck source=/dev/null
	. "$WESTON_CFG"
	ini_tmp="$WESTON_INI.policy.$$"
	weston_write_hmi_ini "$ini_tmp" "$transform"
	ini_changed=1
	if [ -f "$WESTON_INI" ] && cmp -s "$ini_tmp" "$WESTON_INI"; then
		ini_changed=0
	fi
	mv -f "$ini_tmp" "$WESTON_INI"
	if [ "$ini_changed" -eq 0 ]; then
		log "weston.ini unchanged"
		return 1
	fi
	log "weston.ini updated"
	return 0
}

kb="$(input_enabled physical_keyboard_enabled 1)"
mouse="$(input_enabled physical_mouse_enabled 1)"
write_udev_rules "$kb" "$mouse"
reload_udev

weston_changed=0
if refresh_weston_ini; then
	weston_changed=1
fi

if [ "$weston_changed" -eq 1 ] && pidof weston >/dev/null 2>&1; then
	if [ "${INPUT_SKIP_SEAT_RESTART:-0}" = "1" ]; then
		log "seat restart suppressed (boot path)"
	elif [ -x /usr/libexec/hmi/restart-flutter-seat.sh ]; then
		log "weston running — restarting active Flutter seat"
		/usr/libexec/hmi/restart-flutter-seat.sh
	fi
fi

exit 0
