#!/usr/bin/env bash
# Generate board/boot-multi.its from board/rk356x-fit-boards.txt.
# Default board uses @KERNEL_DTB@ so Rockchip mk-fitimage.sh still works for N=1;
# additional boards use @KERNEL_DTB_<board_id>@ substituted by pack-boot-fit-multi.sh.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INVENTORY="${1:-$ROOT/board/rk356x-fit-boards.txt}"
OUT="${2:-$ROOT/board/boot-multi.its}"

die() {
	echo "ERROR: $*" >&2
	exit 1
}

[[ -r "$INVENTORY" ]] || die "missing inventory: $INVENTORY"

boards=()
while IFS= read -r line || [[ -n "$line" ]]; do
	line="${line%%#*}"
	line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
	[[ -z "$line" ]] && continue
	boards+=("$line")
done <"$INVENTORY"

[[ ${#boards[@]} -ge 1 ]] || die "inventory has no board_id entries: $INVENTORY"

default="${FIT_DEFAULT_BOARD:-${boards[0]}}"
found_default=0
for b in "${boards[@]}"; do
	[[ "$b" == "$default" ]] && found_default=1 && break
done
[[ "$found_default" -eq 1 ]] || die "FIT_DEFAULT_BOARD=$default not in inventory"

{
	cat <<'HDR'
/*
 * lws-hmi: multi-configuration boot FIT (platform W5).
 * Generated by scripts/generate-boot-fit-its.sh — do not hand-edit;
 * change board/rk356x-fit-boards.txt and regenerate.
 *
 * Shared kernel + resource; one flat_dt + named conf per inventory board_id.
 * Default conf == product board_id (ynh960). Startup DT stays in FIT (not OEM).
 */
/dts-v1/;
/ {
    description = "U-Boot FIT multi-DT for rk356x family";

    images {
        kernel {
            data = /incbin/("@KERNEL_IMG@");
            type = "kernel";
            arch = "arm64";
            os = "linux";
            compression = "none";
            entry = <0xffffff01>;
            load = <0xffffff01>;

            hash {
                algo = "sha256";
            };
        };

        resource {
            data = /incbin/("@RESOURCE_IMG@");
            type = "multi";
            arch = "arm64";
            compression = "none";

            hash {
                algo = "sha256";
            };
        };
HDR

	for b in "${boards[@]}"; do
		if [[ "$b" == "$default" ]]; then
			dtb_token="@KERNEL_DTB@"
		else
			dtb_token="@KERNEL_DTB_${b}@"
		fi
		cat <<EOF

        fdt-${b} {
            data = /incbin/("${dtb_token}");
            type = "flat_dt";
            arch = "arm64";
            compression = "none";
            load = <0xffffff00>;

            hash {
                algo = "sha256";
            };
        };
EOF
	done

	cat <<EOF

    };

    configurations {
        default = "${default}";
EOF

	for b in "${boards[@]}"; do
		cat <<EOF

        ${b} {
            description = "board_id=${b}";
            rollback-index = <0x00>;
            fdt = "fdt-${b}";
            kernel = "kernel";
            multi = "resource";

            signature {
                algo = "sha256,rsa2048";
                padding = "pss";
                key-name-hint = "dev";
                sign-images = "fdt", "kernel", "multi";
            };
        };
EOF
	done

	cat <<'FTR'
    };
};
FTR
} >"$OUT"

echo "generate-boot-fit-its: wrote $OUT (boards=${boards[*]}; default=$default)"
