import 'dart:io';

import 'package:cyber_hal/network/proxy.dart';
import 'package:cyber_hal/src/linux/lws_trace.dart';

/// System proxy: write [confPath] + env/profile/systemd drop-ins in Dart.
///
/// Persistence and boot restore are in-HAL ([restoreFromDisk]). No apply-proxy
/// script dependency.
class LinuxProxy implements Proxy {
  LinuxProxy({
    this.confPath = '/var/lib/network/proxy.conf',
    this.envFilePath = '/etc/network/proxy.env',
    this.profilePath = '/etc/profile.d/zz-network-proxy.sh',
    this.etcEnvironmentPath = '/etc/environment',
    this.systemdDropinPath =
        '/etc/systemd/system.conf.d/10-network-proxy.conf',
    /// Optional override — when set and present, used instead of in-HAL apply.
    this.applyPath,
  });

  final String confPath;
  final String envFilePath;
  final String profilePath;
  final String etcEnvironmentPath;
  final String systemdDropinPath;
  final String? applyPath;

  @override
  Future<ProxySettings> getSettings() async {
    try {
      final f = File(confPath);
      if (!await f.exists()) {
        return const ProxySettings();
      }
      return _parse(await f.readAsString());
    } catch (_) {
      return const ProxySettings();
    }
  }

  @override
  Future<void> setSettings(ProxySettings settings) async {
    final buf = StringBuffer()
      ..writeln('enabled=${settings.enabled}')
      ..writeln('# written by LinuxProxy');
    void writeUri(String key, ProxyUri? u) {
      if (u == null) {
        return;
      }
      buf.writeln('$key=${_formatUri(u)}');
    }

    writeUri('http_proxy', settings.httpProxy);
    writeUri('https_proxy', settings.httpsProxy);
    writeUri('ftp_proxy', settings.ftpProxy);
    writeUri('all_proxy', settings.allProxy);
    if (settings.noProxy.isNotEmpty) {
      buf.writeln('no_proxy=${settings.noProxy.join(',')}');
    }
    final dir = File(confPath).parent;
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
    await File(confPath).writeAsString(buf.toString(), flush: true);
    await _applyFromConf(clear: false);
  }

  /// Re-apply env/profile/systemd drop-ins from existing [confPath] (boot restore).
  Future<void> restoreFromDisk() => _applyFromConf(clear: false);

  @override
  Future<void> clear() async {
    final dir = File(confPath).parent;
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
    await File(confPath).writeAsString('enabled=false\n', flush: true);
    await _applyFromConf(clear: true);
  }

  Future<void> _applyFromConf({required bool clear}) async {
    final helper = applyPath;
    if (helper != null && helper.isNotEmpty && await File(helper).exists()) {
      final r = await Process.run(
        helper,
        clear ? const <String>['clear'] : const <String>[],
      );
      if (r.exitCode != 0) {
        throw StateError('apply-proxy helper failed: ${r.stderr}');
      }
      return;
    }
    if (clear) {
      await _clearExports();
      lwsTrace('proxy: cleared env exports');
      return;
    }
    final settings = await getSettings();
    if (!settings.enabled) {
      await _clearExports();
      lwsTrace('proxy: disabled — cleared exports');
      return;
    }
    await _writeExports(settings);
    lwsTrace('proxy: applied from $confPath → $envFilePath');
  }

  Future<void> _clearExports() async {
    for (final path in [envFilePath, profilePath, systemdDropinPath]) {
      try {
        final f = File(path);
        if (await f.exists()) {
          await f.delete();
        }
      } catch (_) {}
    }
    await _stripEtcEnvironment();
  }

  Future<void> _writeExports(ProxySettings s) async {
    final lines = <String>[];
    void addPair(String key, ProxyUri? u) {
      if (u == null) {
        return;
      }
      final uri = _formatUri(u);
      lines.add('$key=$uri');
      lines.add('${key.toUpperCase()}=$uri');
    }

    addPair('http_proxy', s.httpProxy);
    addPair('https_proxy', s.httpsProxy);
    addPair('ftp_proxy', s.ftpProxy);
    addPair('all_proxy', s.allProxy);
    if (s.noProxy.isNotEmpty) {
      final np = s.noProxy.join(',');
      lines.add('no_proxy=$np');
      lines.add('NO_PROXY=$np');
    }

    final envBody = StringBuffer()
      ..writeln('# Generated by LinuxProxy — sourced by profile.d / EnvironmentFile');
    for (final line in lines) {
      envBody.writeln(line);
    }

    await File(envFilePath).parent.create(recursive: true);
    await File(envFilePath).writeAsString(envBody.toString(), flush: true);

    await File(profilePath).parent.create(recursive: true);
    await File(profilePath).writeAsString(
      '# Generated by LinuxProxy\n'
      'if [ -f $envFilePath ]; then\n'
      '	set -a\n'
      '	# shellcheck disable=SC1091\n'
      '	. $envFilePath\n'
      '	set +a\n'
      'fi\n',
      flush: true,
    );

    await _stripEtcEnvironment();
    final etc = File(etcEnvironmentPath);
    final existing = await etc.exists() ? await etc.readAsString() : '';
    final merged = StringBuffer(existing);
    if (existing.isNotEmpty && !existing.endsWith('\n')) {
      merged.writeln();
    }
    for (final line in lines) {
      merged.writeln(line);
    }
    await etc.parent.create(recursive: true);
    await etc.writeAsString(merged.toString(), flush: true);

    await File(systemdDropinPath).parent.create(recursive: true);
    final envQuoted = lines.map((l) => '"$l"').join(' ');
    await File(systemdDropinPath).writeAsString(
      '[Manager]\nDefaultEnvironment=$envQuoted\n',
      flush: true,
    );
  }

  Future<void> _stripEtcEnvironment() async {
    final etc = File(etcEnvironmentPath);
    if (!await etc.exists()) {
      return;
    }
    final keys = {
      'http_proxy',
      'https_proxy',
      'ftp_proxy',
      'all_proxy',
      'no_proxy',
      'HTTP_PROXY',
      'HTTPS_PROXY',
      'FTP_PROXY',
      'ALL_PROXY',
      'NO_PROXY',
    };
    final kept = <String>[];
    for (final line in (await etc.readAsString()).split('\n')) {
      final t = line.trim();
      if (t.isEmpty) {
        kept.add(line);
        continue;
      }
      final i = t.indexOf('=');
      if (i <= 0) {
        kept.add(line);
        continue;
      }
      final key = t.substring(0, i);
      if (keys.contains(key)) {
        continue;
      }
      kept.add(line);
    }
    var out = kept.join('\n');
    if (out.isNotEmpty && !out.endsWith('\n')) {
      out = '$out\n';
    }
    await etc.writeAsString(out, flush: true);
  }

  static String _formatUri(ProxyUri u) {
    final scheme = switch (u.scheme) {
      ProxyScheme.http => 'http',
      ProxyScheme.https => 'https',
      ProxyScheme.ftp => 'ftp',
      ProxyScheme.socks4 => 'socks4',
      ProxyScheme.socks4a => 'socks4a',
      ProxyScheme.socks5 => 'socks5',
      ProxyScheme.socks5h => 'socks5h',
    };
    final auth = (u.username != null && u.username!.isNotEmpty)
        ? '${u.username}${u.password != null ? ':${u.password}' : ''}@'
        : '';
    return '$scheme://$auth${u.host}:${u.port}';
  }

  static ProxySettings _parse(String text) {
    var enabled = false;
    ProxyUri? http;
    ProxyUri? https;
    ProxyUri? ftp;
    ProxyUri? all;
    var noProxy = <String>['localhost', '127.0.0.1'];
    for (final line in text.split('\n')) {
      final t = line.trim();
      if (t.isEmpty || t.startsWith('#')) {
        continue;
      }
      final i = t.indexOf('=');
      if (i <= 0) {
        continue;
      }
      final key = t.substring(0, i).trim();
      final val = t.substring(i + 1).trim();
      switch (key) {
        case 'enabled':
          enabled = val == 'true' || val == '1' || val == 'yes';
        case 'http_proxy':
          http = _parseUri(val);
        case 'https_proxy':
          https = _parseUri(val);
        case 'ftp_proxy':
          ftp = _parseUri(val);
        case 'all_proxy':
          all = _parseUri(val);
        case 'no_proxy':
          noProxy = val
              .split(',')
              .map((s) => s.trim())
              .where((s) => s.isNotEmpty)
              .toList();
      }
    }
    return ProxySettings(
      enabled: enabled,
      httpProxy: http,
      httpsProxy: https,
      ftpProxy: ftp,
      allProxy: all,
      noProxy: noProxy,
    );
  }

  static ProxyUri? _parseUri(String raw) {
    if (raw.isEmpty) {
      return null;
    }
    final uri = Uri.tryParse(raw);
    if (uri == null || uri.host.isEmpty) {
      return null;
    }
    final scheme = switch (uri.scheme) {
      'https' => ProxyScheme.https,
      'ftp' => ProxyScheme.ftp,
      'socks4' => ProxyScheme.socks4,
      'socks4a' => ProxyScheme.socks4a,
      'socks5' => ProxyScheme.socks5,
      'socks5h' => ProxyScheme.socks5h,
      _ => ProxyScheme.http,
    };
    return ProxyUri(
      scheme: scheme,
      host: uri.host,
      port: uri.hasPort ? uri.port : 8080,
      username: uri.userInfo.isEmpty
          ? null
          : uri.userInfo.split(':').first,
      password: uri.userInfo.contains(':')
          ? uri.userInfo.split(':').skip(1).join(':')
          : null,
    );
  }
}
