import 'dart:io';

/// Renders systemd-networkd `.network` drop-ins and applies via `networkctl`.
///
/// D11b: portable L3 apply — no iface-named shell wrappers required.
final class NetworkdIpv4Apply {
  NetworkdIpv4Apply({
    this.networkDir = '/etc/systemd/network',
    this.networkctl = 'networkctl',
    this.systemctl = 'systemctl',
    Future<ProcessResult> Function(String exe, List<String> args)? run,
  }) : _run = run ?? ((exe, args) => Process.run(exe, args));

  final String networkDir;
  final String networkctl;
  final String systemctl;
  final Future<ProcessResult> Function(String exe, List<String> args) _run;

  /// Default product metrics (lower wins). Board profile MAY override.
  static int defaultRouteMetric(String iface) {
    switch (iface) {
      case 'wlan0':
        return 100;
      case 'eth0':
        return 2000;
      default:
        return 500;
    }
  }

  /// Prefer this link's DNS for unqualified lookups (dual-homed with eth).
  ///
  /// Lower RouteMetric already prefers Wi‑Fi for packets; without
  /// `Domains=~.`, systemd-resolved may still query ethernet DNS first
  /// (and `/etc/resolv.conf` compatibility lists that server first).
  static bool dnsDefaultRoutePreferred(int routeMetric) => routeMetric < 1000;

  /// Pure render for tests / dry-run.
  ///
  /// When [dns] is non-empty under DHCP, emits Manual DNS override
  /// (`UseDNS=no` + `DNS=`) so lease DNS does not win.
  static String renderNetworkFile({
    required String iface,
    required String mode,
    required int routeMetric,
    String? address,
    String prefix = '24',
    String? gateway,
    String? dns,
  }) {
    final buf = StringBuffer()
      ..writeln('# Generated by cyber_hal NetworkdIpv4Apply — do not edit by hand')
      ..writeln('# RouteMetric=$routeMetric (wifi preferred over ethernet when both have defaults)')
      ..writeln('[Match]')
      ..writeln('Name=$iface')
      ..writeln()
      ..writeln('[Network]');

    final m = mode.trim().toLowerCase();
    final preferDns = dnsDefaultRoutePreferred(routeMetric);
    final manualDns = dns != null && dns.isNotEmpty;
    if (m == 'static') {
      if (address == null || address.isEmpty) {
        throw ArgumentError('static mode requires address');
      }
      buf.writeln('DHCP=no');
      // Dedicated camera link (and other static ifaces): static IPv4 only.
      // IPv6 RA/DHCPv6 can mark the link Failed ("DHCPv6 … No medium") and drop
      // the static address. LinkLocalAddressing=ipv4 would add 169.254/16 APIPA
      // (wrong for IPC eth0 — that is not DHCP fallback, it is IPv4 LL).
      buf.writeln('IPv6AcceptRA=no');
      buf.writeln('LinkLocalAddressing=no');
      buf.writeln('Address=$address/$prefix');
      if (manualDns) {
        buf.writeln('DNS=$dns');
      }
      if (preferDns) {
        buf.writeln('Domains=~.');
      }
      if (gateway != null && gateway.isNotEmpty) {
        buf
          ..writeln()
          ..writeln('[Route]')
          ..writeln('Gateway=$gateway')
          ..writeln('Metric=$routeMetric');
      }
    } else {
      buf
        ..writeln('DHCP=yes')
        ..writeln('IPv6AcceptRA=no');
      if (manualDns) {
        buf.writeln('DNS=$dns');
      }
      if (preferDns) {
        buf.writeln('Domains=~.');
      }
      buf
        ..writeln()
        ..writeln('[DHCPv4]')
        ..writeln(manualDns ? 'UseDNS=no' : 'UseDNS=yes')
        ..writeln('RouteMetric=$routeMetric');
    }
    return buf.toString();
  }

  Future<void> apply({
    required String iface,
    required String mode,
    int? routeMetric,
    String? address,
    String prefix = '24',
    String? gateway,
    String? dns,
    String? prefPath,
  }) async {
    if (iface == 'lo' || iface == 'usb0') {
      throw ArgumentError('refusing iface $iface');
    }
    final metric = routeMetric ?? defaultRouteMetric(iface);
    final body = renderNetworkFile(
      iface: iface,
      mode: mode,
      routeMetric: metric,
      address: address,
      prefix: prefix,
      gateway: gateway,
      dns: dns,
    );

    if (prefPath != null && prefPath.isNotEmpty) {
      await _writePref(
        prefPath,
        mode: mode,
        address: address,
        prefix: prefix,
        gateway: gateway,
        dns: dns,
      );
    }

    final out = Directory(networkDir);
    if (!await out.exists()) {
      await out.create(recursive: true);
    }
    final file = File('$networkDir/50-hmi-$iface.network');
    // networkctl reconfigure drops carrier on RMII eth0; skip when unchanged.
    if (await file.exists()) {
      try {
        if (await file.readAsString() == body) {
          return;
        }
      } catch (_) {
        // Fall through and rewrite.
      }
    }
    await file.writeAsString(body);

    await _run(systemctl, const ['start', 'systemd-networkd.service']);
    await _run(systemctl, const ['start', 'systemd-resolved.service']);
    await _run(networkctl, const ['reload']);
    await _run(networkctl, ['up', iface]);
    final reconf = await _run(networkctl, ['reconfigure', iface]);
    final m = mode.trim().toLowerCase();
    if (m != 'static') {
      // Force a new lease after BSS/SSID change (reconfigure alone may keep stale DNS).
      await _run(networkctl, ['renew', iface]);
      await _waitForIpv4(iface);
    } else if (reconf.exitCode != 0) {
      await _run(networkctl, ['renew', iface]);
    }
  }

  Future<void> setLink({required String iface, required bool up}) async {
    await _run(systemctl, const ['start', 'systemd-networkd.service']);
    final r = await _run(networkctl, [up ? 'up' : 'down', iface]);
    if (r.exitCode != 0) {
      final ip = await _run('ip', ['link', 'set', iface, up ? 'up' : 'down']);
      if (ip.exitCode != 0) {
        throw StateError(
          'networkctl ${up ? 'up' : 'down'} $iface failed: ${r.stderr}',
        );
      }
    }
  }

  Future<void> _writePref(
    String path, {
    required String mode,
    String? address,
    String? prefix,
    String? gateway,
    String? dns,
  }) async {
    final file = File(path);
    await file.parent.create(recursive: true);
    final lines = <String>['mode=${mode.trim().toLowerCase()}'];
    if (address != null && address.isNotEmpty) {
      lines.add('address=$address');
    }
    if (prefix != null && prefix.isNotEmpty) {
      lines.add('prefix=$prefix');
    }
    if (gateway != null && gateway.isNotEmpty) {
      lines.add('gateway=$gateway');
    }
    final manualDns = dns != null && dns.isNotEmpty;
    lines.add('dns_mode=${manualDns ? 'manual' : 'automatic'}');
    if (manualDns) {
      lines.add('dns=$dns');
    } else {
      lines.add('dns=');
    }
    await file.writeAsString('${lines.join('\n')}\n');
  }

  Future<void> _waitForIpv4(String iface) async {
    for (var i = 0; i < 40; i++) {
      final r = await _run('ip', ['-4', '-o', 'addr', 'show', 'dev', iface]);
      final out = '${r.stdout}';
      if (out.contains(' inet ')) {
        return;
      }
      await Future<void>.delayed(const Duration(milliseconds: 250));
    }
  }
}
