import 'dart:io';

/// Writes MediaMTX YAML for IPC PR0/PR1 fan-out (product App path).
final class MediaMtxConfigWriter {
  MediaMtxConfigWriter({
    this.configPath = '/run/hmi/mediamtx.yaml',
  });

  final String configPath;

  /// Returns the config path. Skips rewrite when content is unchanged.
  Future<File> write({required String cameraHost}) async {
    final body = renderYaml(cameraHost: cameraHost);
    final file = File(configPath);
    await file.parent.create(recursive: true);
    if (await file.exists()) {
      final existing = await file.readAsString();
      if (existing == body) {
        return file;
      }
    }
    await file.writeAsString(body);
    return file;
  }

  static String renderYaml({required String cameraHost}) {
    return '''
# Generated by MediaMtxConfigWriter — do not edit by hand
# camera_ip=$cameraHost
logLevel: info
logDestinations: [stdout]
rtspAddress: :8554
rtmp: no
hls: no
webrtc: no
srt: no

paths:
  camera/pr0:
    source: rtsp://$cameraHost/PR0
    rtspTransport: udp
    sourceOnDemand: no
  camera/pr1:
    source: rtsp://$cameraHost/PR1
    rtspTransport: udp
    sourceOnDemand: no
''';
  }
}
